version: '3.1'

services:

  db:
    image: postgres
    container_name: postegres-db
    ports: 
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"] 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: products
